### ISSUE TITLE
创建创建超级用户报错

### ISSUE THREAD

**Issue by 9dre4m** [hzlifeng1/DiffTestPlatform#3]
Traceback (most recent call last):
  File "H:\soft\Python\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "H:\soft\Python\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "H:\soft\Python\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "H:\soft\Python\lib\site-packages\MySQLdb\cursors.py", line 312, in _query
    db.query(q)
  File "H:\soft\Python\lib\site-packages\MySQLdb\connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1364, "Field 'pwd' doesn't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "H:\soft\Python\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "H:\soft\Python\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "H:\soft\Python\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "H:\soft\Python\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 61, in execute
    return super().execute(*args, **options)
  File "H:\soft\Python\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "H:\soft\Python\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 156, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "H:\soft\Python\lib\site-packages\django\contrib\auth\models.py", line 162, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "H:\soft\Python\lib\site-packages\django\contrib\auth\models.py", line 145, in _create_user
    user.save(using=self._db)
  File "H:\soft\Python\lib\site-packages\django\contrib\auth\base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "H:\soft\Python\lib\site-packages\django\db\models\base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "H:\soft\Python\lib\site-packages\django\db\models\base.py", line 779, in save_base
    force_update, using, update_fields,
  File "H:\soft\Python\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "H:\soft\Python\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "H:\soft\Python\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "H:\soft\Python\lib\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "H:\soft\Python\lib\site-packages\django\db\models\sql\compiler.py", line 1332, in execute_sql
    cursor.execute(sql, params)
  File "H:\soft\Python\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "H:\soft\Python\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "H:\soft\Python\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "H:\soft\Python\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "H:\soft\Python\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "H:\soft\Python\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "H:\soft\Python\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "H:\soft\Python\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "H:\soft\Python\lib\site-packages\MySQLdb\cursors.py", line 312, in _query
    db.query(q)
  File "H:\soft\Python\lib\site-packages\MySQLdb\connections.py", line 224, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1364, "Field 'pwd' doesn't have a default value")

**Comment by hzlifeng1** [comment]
不知道你mysql是什么版本的，根据意思应该是数据库表里pwd字段为null了，应该有个默认值。但是我记得我创建的表里没有pwd这个字段，你最好先检查一下你的mysql数据库
